# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: JCypher

# Short description (goes below the title; it will also be used in the RSS feed)
description: JCypher Project Home.

# Your name, as you want it to appear underneath each post and in the footer
author: Wolfgang Schuetzelhofer

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://yourdomain.com/

#### Under the Hood Stuff #####

# Use rdiscount as the markdown engine because it generates html5 compliant code for stuff like footnotes
# If you use maroku (default engine) some of your generated pages may not validate or lint as html5
# If you don't have it install it via gem install rdiscount
markdown: rdiscount

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

pygments: true

# How many articles do you wish to appear on the front page:
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.md, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
